project_name: determined-master

before:
  hooks:
    - make pre-package

snapshot:
  name_template: "{{ .Tag }}"

builds:
  - main: ./cmd/determined-master
    ldflags:
      - -X github.com/determined-ai/determined/master/version.Version={{.Env.VERSION}}
      - -X github.com/determined-ai/determined/master/internal/config.DefaultSegmentMasterKey={{.Env.DET_SEGMENT_MASTER_KEY}}
      - -X github.com/determined-ai/determined/master/internal/config.DefaultSegmentWebUIKey={{.Env.DET_SEGMENT_WEBUI_KEY}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64
  - main: ./cmd/determined-gotmpl
    id: determined-gotmpl
    binary: determined-gotmpl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - ppc64

archives:
  - wrap_in_directory: "true"
    rlcp: true
    files:
      - src: "packaging/master.yaml"
        dst: "etc/determined/"
        strip_parent: true

      - src: "packaging/determined-master.service"
        dst: "lib/systemd/system/"
        strip_parent: true
      - src: "packaging/determined-master.socket"
        dst: "lib/systemd/system/"
        strip_parent: true
      - src: "packaging/LICENSE"
        strip_parent: true
      - src: "static/**/*"
        dst: "share/static"
      - src: "build/**/*"
        dst: "share"

nfpms:
  - maintainer: "Determined AI <hello@determined.ai>"
    formats:
      - deb
      - rpm
    contents:
      - src: "packaging/master.yaml"
        dst: "/etc/determined/master.yaml"
        type: config|noreplace
        file_info:
            mode: 0600
      - src: "build/**/*"
        dst: "/usr/share/determined/master"
      - src: "static/**/*"
        dst: "/usr/share/determined/master/static"
      - src: "packaging/determined-master.service"
        dst: "/lib/systemd/system/determined-master.service"
      - src: "packaging/determined-master.socket"
        dst: "/lib/systemd/system/determined-master.socket"

      - src: "packaging/LICENSE"
        dst: "/usr/share/doc/determined-master/copyright"
        packager: deb

      - src: "packaging/LICENSE"
        dst: "/usr/share/licenses/determined-master/LICENSE"
        packager: rpm

    overrides:
      deb:
        scripts:
          postinstall: packaging/debian/master.postinst
          preremove: packaging/debian/master.prerm
          postremove: packaging/debian/master.postrm

dockers:
  # amd64
  - goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --builder=buildx-build-sharedcluster
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64-shared-cluster"
    extra_files:
      - "packaging/master.yaml"
      - "packaging/LICENSE"
      - "build"
      - "static"
    ids:
      - determined-master
      - determined-gotmpl

docker_manifests:
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-shared-cluster"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64-shared-cluster"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.ShortCommit}}-shared-cluster"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64-shared-cluster"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.Env.VERSION}}-shared-cluster"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64-shared-cluster"
  - name_template: "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:latest-shared-cluster"
    image_templates:
      - "{{.Env.DOCKER_REPO}}/{{.ProjectName}}:{{.FullCommit}}-amd64-shared-cluster"
